name: Configure Branch Protection

on:
  push:
    branches: [main, develop]

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Configure branch protection
        uses: actions/github-script@v7
        with:
          script: |
            // Configurar proteção para branch main
            github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: [
                  'Quality Checks',
                  'Deploy to Vercel'
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false
            });
            
            // Configurar proteção para branch develop
            github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'develop',
              required_status_checks: {
                strict: true,
                contexts: [
                  'Quality Checks'
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false
            });
            
            console.log('Branch protection configured successfully');
