name: Configure Branch Protection

on:
  push:
    branches: [main, develop]

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Protect main branch
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: [
                  'Quality Checks',
                  'Type Check',
                  'Lint',
                  'Tests',
                  'Security Audit'
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 2,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_reviewers: ['senior-dev', 'tech-lead']
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false
            });
      
      - name: Protect develop branch
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'develop',
              required_status_checks: {
                strict: true,
                contexts: [
                  'Quality Checks',
                  'Type Check',
                  'Lint',
                  'Tests'
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false
              },
              restrictions: null
            });
